### ISSUE TITLE
Documentation for usage with socket.io-client.

### ISSUE THREAD

**Issue by n2liquid** [hden/socketio-wildcard#13]
I noticed the readme file only mentions how to register socketio-wildcard to an IO server, not client.

I've tried to guess which functions to call, but I can't find any middleware-related APIs on the IO client objects (which doesn't surprise me). So how does it work?

This should be clear in the readme...

**Comment by hden** [comment]
Fixed in v0.3.0.

**Comment by n2liquid** [comment]
That was quick. Thanks, buddy! :)
