### ISSUE TITLE
Support for UMD module

### ISSUE THREAD

**Issue by gabrielstuff** [hden/socketio-wildcard#24]
Hi !
This plugin is fairly simple and we are happy to use it for spacebro: https://github.com/soixantecircuits/spacebro
Nonetheless, we would like to add support for UMD and thus allow to use the module with a basic `<script src="">` tag.

What do you think about it?

Thanks !

**Comment by hden** [comment]
What's your use case?

Exporting a browserified module will be easy here, but it might complicate downstream module bundling.

I usually writes modules in node or ES6 format and let a bundler (e.g. browserify, rollup, webpack) produce the final product.

**Comment by gabrielstuff** [comment]
We use webpack/browserify to create large scale application.
We also like to be able to show simple use case / or little prototype using
codepen.io or simply a html file with src pointing to cdnjs
For sure it will complicate the bundling.

As the lib is really tiny we might ship it include instead of treating it
as external. But I'd prefer to avoid such a scenario.
Le mer. 21 sept. 2016 à 03:36, Hao-kang Den <notifications@github.com> a
écrit :

**Comment by hden** [comment]
For that use case, https://wzrd.in/standalone/socketio-wildcard@latest will do.

**Comment by hden** [comment]
Just created a pen for demo http://codepen.io/anon/pen/LRbAzy

**Comment by gabrielstuff** [comment]
Wow ! https://wzrd.in/ looks great. Let me take a closer look at this.

**Comment by gabrielstuff** [comment]
It is perfect!
