### ISSUE TITLE
Fails to catch broadcast messages

### ISSUE THREAD

**Issue by Kryten0807** [hden/socketio-wildcard#26]
I ran into an issue while trying to implement this package with broadcast messages sent from the server.

I tinkered with the tests a bit to replicate the problem. Here's how to reproduce it:

In `test/index.js`, on line 87, change

    socket.emit('foo', { bar: 'baz' })

to

    socket.broadcast.emit('foo', { bar: 'baz' })

The test now times out.

Unfortunately, I wasn't sure how to extend the test code to include this as a new test case...

**Comment by hden** [comment]
The broadcast API is not well documented, can you try to join a room first?
https://github.com/socketio/socket.io/blob/d026c00d05fbd77d28962dd9336da34ab63bda40/test/socket.io.js#L2010-L2017

**Comment by Kryten0807** [comment]
I suspect the problem is not with your library but with the documentation for socket.io. I'm following their examples, but I don't think it works the way they say it does :-p

At any rate, I came up with a different approach to solve my problem, so I'm not going to pursue this any further. I'll leave it up to you if you want to leave this issue open. Thanks for your help.
