### ISSUE TITLE
Syntax in example isn't working

### ISSUE THREAD

**Issue by ddibiase** [hden/socketio-wildcard#32]
Hi there,

Having some trouble replicating the example on the README. I tried this:

    var io         = require('socket.io')();
    var middleware = require('socketio-wildcard')();

    io.use(middleware);

    io.on('connection', function(socket) {
      socket.on('*', function(packet){
        // client.emit('foo', 'bar', 'baz')
        packet.data === ['foo', 'bar', 'baz']
      });
    });

    io.listen(8000);

Throws an error that io.use is not defined on Namespace:

    TypeError: Cannot convert undefined or null to object
    at Namespace.use (/Users/ddibiase-macbook/Projects/dfx-api/node_modules/socket.io/lib/namespace.js:103:21)

Seems like you can only bind on the socket itself with use after the connection. Unless I'm doing something incorrectly here?

    import io from 'socket.io';
    import middleware from 'socketio-wildcard';

    this.io = io(this.config.port);
    this.io.use(middleware());
    this.io.on('connection', this.socketConnect);

I'd prefer not to bind middleware on the socket directly and have it bind across all sockets. I have to write a middleware binding for my class structure to route requests.

Thanks.

**Comment by hden** [comment]
Which version of node.js and Socket.io are you using?
Can you try https://github.com/hden/socketio-wildcard/blob/master/test/index.js#L14-L18 ?

**Comment by hden** [comment]
Works for my current environment and CI (TravisCI).
* Node.js@v8.1.0
* socket.io@2.0.1
* socket.io-client@2.0.1

```js
// server.js
var io         = require('socket.io')()
var middleware = require('./')() // socketio-wildcard @ master

io.use(middleware)

io.on('connection', function(socket) {
  socket.on('*', function(packet){
    console.log(packet.data) // [ 'foo', 'bar', 'baz' ]
  })
})

io.listen(8000)
```


```js
// client.js
var connect = require('socket.io-client')
var client = connect('http://localhost:8000')
client.emit('foo', 'bar', 'baz')
```
