### ISSUE TITLE
Client Native Events (like connect) aren't caught

### ISSUE THREAD

**Issue by tobiasmuecksch** [hden/socketio-wildcard#34]
Hello,

when I use the wildcard (like in the following example) native socket events like `disconnect`, `connect`, `connect_error`, `connect_timeout`, `reconnect` etc. aren't caught by the wildcard.

Is this behavior intended? If yes - why? -OR- Is this a bug?

Thank you in advance!

**Example code:**
```
var io = require('socket.io-client');
var socket = io('http://localhost');
// piggyback using the event-emitter bundled with socket.io client
var patch = require('socketio-wildcard')(io.Manager);
patch(socket);

socket.on('*', function(packet){ 
   console.log('EVENT FIRED', packet); // connect, disconnect etc. events do not show in the console
})
```

**Comment by hden** [comment]
Yes, this module is designed to be a very simple workaround for user space packets via replacing `socket.onevent()`, which handles `parser.EVENT` and `parser.BINARY_EVENT`.

To get the internal events such as `ACK`, `DISCONNECT`, `ERROR` you might want to modify `socket.onpacket()` instead.
