### ISSUE TITLE
Can/how this work in browser client?

### ISSUE THREAD

**Issue by lslzl3000** [hden/socketio-wildcard#36]
Any example in browser client?

**Comment by hden** [comment]
https://github.com/hden/socketio-wildcard#client

**Comment by lslzl3000** [comment]
I mean something like browserify, no 'require', just use <script> to manage socket.io client

**Comment by hden** [comment]
I see. Then perhaps you should try browserify or something similar.

There is a service called `wzrd.in` which basically browserify any nom package for you.

`<script src="https://wzrd.in/standalone/socketio-wildcard@latest">`

http://jsbin.com/mocomawibe/edit?html,js,output

**Comment by lslzl3000** [comment]
@hden Thanks. I tried to browserify this module by `browserify index.js`, but the result does not export the 'socketioWildcard' word, so I don't know how to use it. 
But the `wzrd.in` service gives the API.
