### ISSUE TITLE
socket.on('*', ... didn't work in my case.

### ISSUE THREAD

**Issue by qiulang** [hden/socketio-wildcard#37]
I didn't know what I had done wrong. `socket.on('*', function(packet){ }) ` didn't work in my case. I just use it like readme says. I added `console.log('a user connected ' + socket.id);` to make sure a socket does connect, but it didn't enter into `socket.on('*', function(packet){ }) `

**Comment by hden** [comment]
What's your node version, socket.io (server) version, and socket.io (client) version?

1. Can you try clone this repo and run `npm install && npm test`?
2. If that didn't work, would you kindly provide a minimal code sample that reproduce your problem?

**Comment by qiulang** [comment]
Hi, I finally figured it out that it was because I used namespace. Then instead of using io.use(middleware) I should use io.of('/ns').use(middleware); otherwise in this namespace socket.on('*' won't work.

BTW I used socket.io 2.0
