### ISSUE TITLE
[BUG] socket.use no work !!

### ISSUE THREAD

**Issue by ipengyo** [hden/socketio-wildcard#38]
use the module 
`frontSocketIoServer.use(socketioWildcard());`

Will lead to

![image](https://user-images.githubusercontent.com/9323722/37499652-db16d698-28ff-11e8-90c0-46d5eaa5c721.png)

no work !!!!!!

**Comment by hden** [comment]
Assuming what you meant is that using the socketio-wildcard middleware somehow broke your auth middleware. I'd need more information to debug. Would you kindly provide a minimal sample code to reproduce the problem, i.e.

1. Which version of socket.io are you using for the server?
1. Which version of socket.io are you using for the client?
1. In what sequence did you initiated the middlewares? (socketio-wildcard after auth or vise-versa?)
1. Did you modify the packet within the wildcard callback?

**Comment by ipengyo** [comment]
my Solution 
```

const wildcard = function () {
  function _makeonevent (oldOnevent) {
    return function (packet) {
      var args = packet.data || [];
      packet.data = ["*"].concat(args);
      return oldOnevent.call(this, packet);      // additional call to catch-all
    }
  }
  return function (socket, next) {
    if (!socket.hasReplaceOneventFn) {
      let oldOnevent = socket.onevent;
      socket.onevent = _makeonevent(oldOnevent);
      socket.hasReplaceOneventFn = true;
    }
    return next ? next() : null
  }
}
```

` let oldOnevent = socket.onevent;`

You need to call the original method to trigger the socket.use

**Comment by hden** [comment]
Calling the original `onevent()` function will effectively acknowledge the packet twice. A better approach might be calling `this.dispatch()` within our modified version.

See: https://github.com/socketio/socket.io/blob/master/lib/socket.js#L363

**Comment by ipengyo** [comment]
@hden  Thank you, your idea is good. But will change the previous debug log can not be executed

**Comment by ipengyo** [comment]
```
return function (packet) {
      var args = packet.data || [];
      if (null != packet.id) {
        args.push(this.ack(packet.id));
      }
      packet.data = args.unshit('*') //// additional call to catch-all
      return this.dispatch(args);
    }
```

I only need to monitor the `eventName *` and then do the event distribution processing under this event
