### ISSUE TITLE
Possible to dictate the precendence of '*' handler?

### ISSUE THREAD

**Issue by carpii** [hden/socketio-wildcard#5]
From what I can see, the '*' catchall handler always runs after all other event handlers.

Is there a way to allow the catchall handler to run before all other event handlers (ie for generic RVC/EMIT logging?)

It would be a nice feature, although I suspect there's underlying reasons why its like that

**Comment by hden** [comment]
Socket.io ships with internal logging via [debug](https://www.npmjs.com/package/debug).
See [document](http://socket.io/docs/logging-and-debugging/) for detail.

**Comment by carpii** [comment]
Thankyou, I will look into that.
