### ISSUE TITLE
question about emit

### ISSUE THREAD

**Issue by kadko** [hden/socketio-wildcard#56]
```
emit.call(this, '*', packet)
return emit.apply(this, args)
```

why emit called twice?

**Comment by hden** [comment]
First one is for the wildcard `*` event. The second one is for the regular event name. To keep things simple, this library choose not to incorporate a fancy event dispatcher. Instead, it use a fixed event name emitted along with every native event.

**Comment by kadko** [comment]
Then same event callback function runs twice isnt it?

**Comment by hden** [comment]
Nope.

**Comment by hden** [comment]
If you would be so kind to checkout the tests

https://github.com/hden/socketio-wildcard/blob/master/test/index.js#L49-L58

each of the callback is called once.
