### ISSUE TITLE
Compatibility issue with socketio-auth

### ISSUE THREAD

**Issue by z3phyro** [hden/socketio-wildcard#61]
Here is the thing. When I try to use socketio-auth and socketio-wildcard, it wont work on the deployed version of my project. The "deployment server" has node v8.12.0 and my local computer has v8.11.3. It does work in my local computer, and as soon as I comment the use middleware line the server starts working properly but it just wont connect when having this 2 plugins. I'll put a sample of the conf I have.

```
const io = require('socket.io')(),
    middleware = require('socketio-wildcard')();

require('socketio-auth')(io, {
    authenticate: authenticate,
    postAuthenticate: postAuthenticate,
    disconnect: disconnect,
    timeout: 1000
});

io.use(middleware);

io.listen(8030);
```

And the post authenticate function which is only called after the connection is validated.

```
function postAuthenticate(client, data) {
    client.on('*', data => {
          // Do something
    }
}
```

**Comment by hden** [comment]
This middleware was written in days when you need to monkey patch the namespace to capture all the events. After socket.io v2.0.4, you could simply use a socket-level middleware instead. See https://github.com/hden/socketio-wildcard#sunsetting

**Comment by z3phyro** [comment]
@hden This solved my problems. I just overlooked it. Thanks.
