### ISSUE TITLE
* wildcard as part of a string

### ISSUE THREAD

**Issue by AngelKyriako** [hden/socketio-wildcard#9]
From a quick glance at the source this middleware should not work for event listeners that contain the '*' character.

```
case:
      emit event: _hello_world_
      listening to event: '*hello*'
```

Are there any plans for the plugin to support this scenario?

We are currently using socket.io 0.9.X and I would like to know if this is supported in order to know if it worths it for us to migrate to socket.io 1.X.

Thank you

**Comment by hden** [comment]
Short answer: No.
Long answer: It's very easy to implement an event router.

```js
var io         = require('socket.io')();
var middleware = require('socketio-wildcard')();
// pick a router that fits your use case, EventEmitter2, trie, regex, anything.
var EE         = require('eventemitter2'). EventEmitter2;

io.use(middleware);

var router = new EE();

router.on('hello.*', function() { /* ... */ })

io.on('connection', function(socket) {
  socket.on('*', function(packet){
    router.emit.apply(router, packet.data)
  });
});

io.listen(8000);
```
